### ISSUE TITLE
[Enhancement] Set Artifact name.

### ISSUE THREAD

**Issue by bfeher** [bitrise-steplib/steps-xcode-build-for-simulator#21]
Right now the artifact is named after the Scheme. 
Would it be possible to expose a field for setting the `ArtifactName`?

When I checked out the source, I could see where it was being loaded, but I'm not sure where to use it.

Thanks!

**Comment by bitce** [comment]
Hi @bfeher! Thanks for pointing this out, we've noted this as a feature request!

**Comment by mikeberlin** [comment]
Yes please, would be very helpful. Also, we can offer the option to zip up the artifact? Would make uploading the .app directory to other systems much easier.

**Comment by ofalvai** [comment]
@mikeberlin this is actually an existing feature of the _Deploy to Bitrise.io_ step. Look for the compress artifacts option in the deploy step's config 😉

**Comment by mikeberlin** [comment]
> @mikeberlin this is actually an existing feature of the _Deploy to Bitrise.io_ step. Look for the compress artifacts option in the deploy step's config 😉

Sure, if I wanted to compress **all** the artifacts of the build. But if I want to compress only the .app directory of the _Xcode Build for Simulator_ step, that doesn't seem possible.

Our use case is we want to zip up the .app directory and upload that zip file via a rest api to SauceLabs which kicks off our automated tests. I've been able to do all of this manually via a script step, but it would be very handy to have this step compress the output individually.
