### ISSUE TITLE
Xcode build log not available on build success

### ISSUE THREAD

**Issue by jwelton** [bitrise-steplib/steps-xcode-build-for-simulator#24]
When the build fails, the log is available using `BITRISE_XCODE_RAW_RESULT_TEXT_PATH`. However, when the build is successful, the log is not available. This causes a problem when posting warnings & errors to the GitHub PR. It means PR's introducing warnings but that still compile don't have those warnings posted on the PR, reducing their discoverability before merging.

**Comment by cathyharmon** [comment]
Hello,
BITRISE_XCODE_RAW_RESULT_TEXT_PATH  does not point to the build log.  This points to the raw-xcodebuild-output.log.  Currently this is indeed only available when xcodebuild fails and it is not the entire build log.

The build log itself is available for both successful and failing builds.  It is available from the UI or can be accessed via the API.

cathy

**Comment by jwelton** [comment]
Hi @cathyharmon. Sorry I wasn't very clear. I was indeed referring to the Xcode log, not the Bitrise log.

**Comment by jwelton** [comment]
The Xcode log is what we generate a list of compiler errors and warnings from. Without it on the success case, we're not able to see if anyway warnings were produced during the build. A feature request would be great.

Would you accept PR's? I would be happy to attempt to implement this.

**Comment by cathyharmon** [comment]
Hello,

That would be awesome!  You can find information on contributing at:
https://github.com/bitrise-steplib/.github/blob/main/CONTRIBUTING.md

Of course, if this is something that might be more specific to just you, you can fork the step and make changes and use that.

Thanks,
Cathy
