### ISSUE TITLE
No option to toggle CODE_SIGNING_ALLOWED

### ISSUE THREAD

**Issue by smmcdonald** [bitrise-steplib/steps-xcode-build-for-simulator#30]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is affected? 0.11.6
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

Currently, there is no option to toggle "CODE_SIGNING_ALLOWED=NO", which is required by some CocoaPod frameworks such as Firebase Remote Config to work properly.

### Bitrise info

- Build URL: [_Please share the build URL with us._](https://app.bitrise.io/build/348083c9-69b9-42a1-8d20-dd94bf003465)
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: NO
- Log: Xcode build for simulator

<details>
  <pre>
Running build
$ set -o pipefail && xcodebuild "-workspace" "/Users/vagrant/git/MyProject.xcworkspace" "-scheme" "My Project" "-configuration" "QA" "CODE_SIGNING_ALLOWED=NO" "-destination" "id=5210DB4C-7CD4-4DE7-AC08-6E2F259F04B4" "COMPILER_INDEX_STORE_ENABLE=NO" "clean" "build" | xcpretty
  </pre>
</details>
It is possible to work around this limitation by adding "CODE_SIGNING_ALLOWED=YES" in the 'Additional options for xcodebuild call' under the 'Debug' section but I wouldn't rely on this as it produces a command that looks like this with two CODE_SIGNING_ALLOWED flags that may not always work:

```
xcodebuild "-workspace" "/Users/vagrant/git/MyProject.xcworkspace" "-scheme" "My Project" "-configuration" "QA" "CODE_SIGNING_ALLOWED=NO" "-destination" "id=5210DB4C-7CD4-4DE7-AC08-6E2F259F04B4" "COMPILER_INDEX_STORE_ENABLE=NO" "clean" "build" "CODE_SIGNING_ALLOWED=YES" | xcpretty
```

### Steps to reproduce

Run the build for the simulator step on a project that uses Firebase Remote Config key values. The values should be fetched on app launch but are never called.

**Comment by shams-ahmed** [comment]
@smmcdonald can you provide more context or links on why some Cocoapods frameworks needs this disabled?

**Comment by smmcdonald** [comment]
This is because some frameworks require codesigning in order to produce a valid build product, otherwise, there will be an error:

```
CodeSign error: code signing is required for product type 'Application' in SDK
                'iOS 15.2'
```

and missing _CodeSignature file in the framework.
https://stackoverflow.com/a/11034618/2076025

**Comment by abejfehr** [comment]
I just added `CODE_SIGNING_ALLOWED=YES` in the `xcodebuild_options`

**Comment by shams-ahmed** [comment]
PR #31 will resolve the issue. Expect a new version in the next 48 hours.
