### ISSUE TITLE
[BLOCKER] Unable to find simulator build in the artifact

### ISSUE THREAD

**Issue by breadcomb-app** [bitrise-steplib/steps-xcode-build-for-simulator#44]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 2.0.0
- Is the issue reproducible with the latest version? YES 
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

I'm building a simulator build for my application, however the logs shows it was built successfully, and the artifact is exported to the correct directory.

However, when I check the deploy to Bitrise.io logs, the `.app` build doesn't appear to be there.

### Bitrise info

- Build URL: [_Please share the build URL with us._](https://app.bitrise.io/build/cb9bd93a-91cc-4218-b3fd-b2e5dec0efd2?tab=log)
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES
- Log: 

the log shows it's exporting artifact
<details>
  <pre>
      Copy artifacts from Derived Data to /Users/vagrant/deploy
      [REDACTED]Dev...
      Exporting outputs
      BITRISE_APP_DIR_PATH -> /Users/vagrant/deploy/[REDACTED]Dev.app
      BITRISE_APP_DIR_PATH_LIST -> /Users/vagrant/deploy/[REDACTED]Dev.app
      You can find the exported artifacts in: /Users/vagrant/deploy
  </pre>
</details>

but the deploy to bitrise doesn't show anything

<details>
  <pre>
      Build Artifact deployment mode: deploying the content of the deploy directory
      List of files to deploy (7):
      - /Users/vagrant/deploy/app-dev-debug.apk
      - /Users/vagrant/deploy/[REDACTED]Dev.dSYM.zip
      - /Users/vagrant/deploy/[REDACTED]Dev.ipa
      - /Users/vagrant/deploy/[REDACTED]Dev.xcarchive.zip
      - /Users/vagrant/deploy/export_options.plist
      - /Users/vagrant/deploy/xcodebuild-archive.log
      - /Users/vagrant/deploy/xcodebuild-export-archive.log
-   </pre>
</details>

### Steps to reproduce

1. build a normal react-native app
2. add the Build for Simulator step in

**Comment by lpusok** [comment]
Hello,
Please add the `create-zip` step with the directory path `$BITRISE_APP_DIR_PATH`. This is a missing feature of build-for-simulator. The deploy step only picks up files, not directories.
